### ISSUE TITLE
Furigana is misaligned when used with Autosize

### ISSUE THREAD

**Issue by edmilsonrobson** [jp-netsis/RubyTextMeshPro#2]
When using the Auto Size feature of TMP, the Furigana seems to get misaligned.

**Without Auto Size**
![image](https://user-images.githubusercontent.com/1232107/103655703-6114f300-4f46-11eb-98ea-36a89361952e.png)

**With Auto Size**
![image](https://user-images.githubusercontent.com/1232107/103655737-70943c00-4f46-11eb-97c7-4f377fe58d5f.png)

**Comment by jp-netsis** [comment]
Thank you for your report! Investigate

**Comment by jp-netsis** [comment]
Cause :
Set Autosize -> TMP_TEXT.GetPreferredValues return max size font text size.
Fix :
Set Autosize -> GetPreferredValues to Correct,
and Fixed a delay in updating FontSize by updating the mesh when changing OnValidate.

https://github.com/jp-netsis/RubyTextMeshPro/commit/da2713f50d96042da2647748fc73f474504d1020

**Comment by edmilsonrobson** [comment]
Brilliant work, will test later 😄
