### ISSUE TITLE
Dynamically setting the text won't replace Ruby tags

### ISSUE THREAD

**Issue by edmilsonrobson** [jp-netsis/RubyTextMeshPro#3]
I recently tried changing the text of a `RubyTextMeshProUGUI` component to dynamically replace the Japanese text. Something like this:

`this.japaneseText.text = "<ruby=ほん>本</ruby>`

The expected behavior would be the text changing and properly parsing the ruby tags, but instead, it becomes the literal string "<ruby=ほん>本</ruby>", without the ruby tags parsing.

I solved it by using the `SetTextCustom` method from `RubyTextMeshProUGUI`, but I had to change its visibility from private to public, so I was wondering if there's a better way to do this already in the package or if it's a bug.

Thanks for the great work with this package! 😄

**Comment by jp-netsis** [comment]
`japaneseText.text` is intentionally left as a way to directly rewrite the text in TextMesh Pro.
If you want to insert ruby ​​directly in the source code, use `japaneseText.UnditedText`.
(Add Sample4 Scene)
Regular expressions are used inside the process, so if you use a lot, it will be slow. be careful.
Thank You!

**Comment by edmilsonrobson** [comment]
Ahh, I see. that makes sense. Thanks! 🎉
