### ISSUE TITLE
Furigana not lining up with base text

### ISSUE THREAD

**Issue by Nyankoo** [jp-netsis/RubyTextMeshPro#4]
First of all, thank you for the great asset!

I noticed that our furigana are not correctly aligning with the base text:
![furigana](https://user-images.githubusercontent.com/6652214/133084063-2a5baed8-9e44-47cb-9915-ab73089af6ce.png)

This could be from the font we're using (EPSON 教科書体Ｍ (epkyouka.ttf)).

Is there a way to correctly align the furigana?

**Comment by jp-netsis** [comment]
Thanks for using it from here too!

I also tried (EPSON 教科書体Ｍ (epkyouka.ttf)), but it didn't deviate that much. Do you have any other information?

![Screenshot](https://user-images.githubusercontent.com/36494806/133099294-a9c59b4d-8105-456c-8f8a-eeabaad87dcc.jpg)

The area circled by the red square is my setting.

**Comment by Nyankoo** [comment]
Thank you for looking into this!

I tried to replicate your settings, but even with the same font settings, it seems the `space` tag is 30.025 for you, but 31.2525 for me. Maybe this is where the difference is coming from?

![furigana2](https://user-images.githubusercontent.com/6652214/133109950-ce9bc8ce-9a9e-4490-9a00-b115c4b7d0c0.png)

**Comment by jp-netsis** [comment]
There are many possible reasons for the difference.
The font may have the same name but different, or the coordinates may be off when rendering the font.

The screenshot shows that the font size is 125, so it's not the same as my 120.

The calculation of space is done in the following form.

https://github.com/jp-netsis/RubyTextMeshPro/blob/bf130790bdeb32d310a025f03e824b04d5b6c5c2/Assets/RubyTextMeshPro/Source/RubyTextMeshProUGUI.cs#L84
L84-L91

If the all text size is the same, you may want to review the settings when generating the SDF.

I've tried the following ttf.

https://en.m.fontke.com/family/145119/style/

To generate SDF, only the Demo's ttf was replaced and rebuild.

**Comment by Nyankoo** [comment]
Changing the font size to 120 sadly also didn't changed the alignment.

Did you download the first or second TTF file from the link?

**Comment by jp-netsis** [comment]
I downloaded the first one.

**Comment by Nyankoo** [comment]
Thank you, I could find the issue! The font in our project had the `Spacing Offset` under `Font Weights` set to -10 for some reason, which caused the offset.

Thank you again for the great assistance with this!
